version: '2'

services:
    cache:
      image: redis:latest
      restart: always
    app:
      image: steveyiyo/url-shortener:latest
      restart: always
      ports:
      - 0.0.0.0:7600:7600
      volumes:
        # Mount the config file
        - "/opt/url/.env:/app/.env"
        - "/opt/url/config.yaml:/app/config.yaml"
        # Mount the database volume
        - "/opt/url/data.db:/app/data.db"