version: '2'

services:
    cache:
      image: redis:latest
      restart: always
    app:
      image: steveyiyo/url-shortener:latest
      restart: always
      ports:
        - 0.0.0.0:7600:7600
      volumes:
        - "./data/:/app/data/"
      environment:
        Redis_Addr: "cache:6379"
        Redis_Pwd: ""
        Listen: "0.0.0.0"
        Host: "http://localhost"
        Port: "7600"