version: '2'

services:
    cache:
      image: redis:latest
      restart: always
    app:
      image: steveyiyo/url-shortener:latest
      restart: always
      ports:
      - 0.0.0.0:7600:7600
      volumes:
        - "/opt/url/.env:/app/.env"
        - "/opt/url/config.yaml:/app/config.yaml"